[2024-11-23T01:02:57.609+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-23T01:02:57.645+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_price_prediction.fetch_data scheduled__2024-11-22T00:00:00+00:00 [queued]>
[2024-11-23T01:02:57.653+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_price_prediction.fetch_data scheduled__2024-11-22T00:00:00+00:00 [queued]>
[2024-11-23T01:02:57.654+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2024-11-23T01:02:57.667+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-11-22 00:00:00+00:00
[2024-11-23T01:02:57.673+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stock_price_prediction', 'fetch_data', 'scheduled__2024-11-22T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/stock_price_prediction_dag.py', '--cfg-path', '/tmp/tmpjeuw2e4k']
[2024-11-23T01:02:57.676+0000] {standard_task_runner.py:91} INFO - Job 16: Subtask fetch_data
[2024-11-23T01:02:57.677+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=653) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-23T01:02:57.677+0000] {standard_task_runner.py:63} INFO - Started process 654 to run task
[2024-11-23T01:02:57.726+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_price_prediction.fetch_data scheduled__2024-11-22T00:00:00+00:00 [running]> on host c3907abb67cc
[2024-11-23T01:02:57.806+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_price_prediction' AIRFLOW_CTX_TASK_ID='fetch_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-22T00:00:00+00:00'
[2024-11-23T01:02:57.807+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-23T01:02:58.810+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/vnstock/__init__.py:18 UserWarning: Vui lòng chuyển đổi sang Vnstock3 thế hệ mới (3.1.0) với câu lệnh: `pip install vnstock3 --upgrade`.
Từ 1/1/2025, vnstock3 sẽ được cài đặt khi sử dụng cú pháp `pip install vnstock` thay cho Vnstock Legacy hiện tại.
Xem chi tiết [chuyển đổi sang vnstock3](https://vnstocks.com/docs/tai-lieu/migration-chuyen-doi-sang-vnstock3).
Phiên bản Vnstock Legacy (0.2.9.2.3) bạn đang sử dụng sẽ không được nâng cấp thêm.
Từ 7/10/2024 Vnstock giới thiệu nhóm Facebook Cộng đồng Vnstock, tham gia thảo luận tại đây: https://www.facebook.com/groups/vnstock.official
[2024-11-23T01:02:59.023+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-23T01:02:59.024+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_price_prediction_dag.py", line 28, in fetch_data_task
    fetch_data(stock_name)
  File "/external_files/scripts/fetch_data.py", line 6, in fetch_data
    data.to_csv(f"data/raw/{stock_name}_data.csv", index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 739, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 604, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'data/raw'
[2024-11-23T01:02:59.043+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_price_prediction, task_id=fetch_data, run_id=scheduled__2024-11-22T00:00:00+00:00, execution_date=20241122T000000, start_date=20241123T010257, end_date=20241123T010259
[2024-11-23T01:02:59.055+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 16 for task fetch_data (Cannot save file into a non-existent directory: 'data/raw'; 654)
[2024-11-23T01:02:59.095+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-23T01:02:59.115+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-23T01:02:59.118+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-11-23T01:36:55.840+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-23T01:36:55.870+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_price_prediction.fetch_data scheduled__2024-11-22T00:00:00+00:00 [queued]>
[2024-11-23T01:36:55.877+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_price_prediction.fetch_data scheduled__2024-11-22T00:00:00+00:00 [queued]>
[2024-11-23T01:36:55.878+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-11-23T01:36:55.890+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-11-22 00:00:00+00:00
[2024-11-23T01:36:55.896+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stock_price_prediction', 'fetch_data', 'scheduled__2024-11-22T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/stock_price_prediction_dag.py', '--cfg-path', '/tmp/tmphti5eot7']
[2024-11-23T01:36:55.899+0000] {standard_task_runner.py:91} INFO - Job 20: Subtask fetch_data
[2024-11-23T01:36:55.900+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=164) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-23T01:36:55.901+0000] {standard_task_runner.py:63} INFO - Started process 167 to run task
[2024-11-23T01:36:55.943+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_price_prediction.fetch_data scheduled__2024-11-22T00:00:00+00:00 [running]> on host ad983beda88b
[2024-11-23T01:36:56.024+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_price_prediction' AIRFLOW_CTX_TASK_ID='fetch_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-22T00:00:00+00:00'
[2024-11-23T01:36:56.026+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-23T01:36:58.453+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/vnstock/__init__.py:18 UserWarning: Vui lòng chuyển đổi sang Vnstock3 thế hệ mới (3.1.0) với câu lệnh: `pip install vnstock3 --upgrade`.
Từ 1/1/2025, vnstock3 sẽ được cài đặt khi sử dụng cú pháp `pip install vnstock` thay cho Vnstock Legacy hiện tại.
Xem chi tiết [chuyển đổi sang vnstock3](https://vnstocks.com/docs/tai-lieu/migration-chuyen-doi-sang-vnstock3).
Phiên bản Vnstock Legacy (0.2.9.2.3) bạn đang sử dụng sẽ không được nâng cấp thêm.
Từ 7/10/2024 Vnstock giới thiệu nhóm Facebook Cộng đồng Vnstock, tham gia thảo luận tại đây: https://www.facebook.com/groups/vnstock.official
[2024-11-23T01:36:58.457+0000] {fetch_data.py:10} INFO - Directory data/raw created or already exists.
[2024-11-23T01:36:58.715+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-23T01:36:58.716+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-23T01:36:58.724+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=stock_price_prediction, task_id=fetch_data, run_id=scheduled__2024-11-22T00:00:00+00:00, execution_date=20241122T000000, start_date=20241123T013655, end_date=20241123T013658
[2024-11-23T01:36:58.758+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-23T01:36:58.780+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-23T01:36:58.782+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
