[2024-11-22T16:15:33.304+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-22T16:15:33.351+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_price_prediction.fetch_data manual__2024-11-22T16:15:32.032601+00:00 [queued]>
[2024-11-22T16:15:33.359+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_price_prediction.fetch_data manual__2024-11-22T16:15:32.032601+00:00 [queued]>
[2024-11-22T16:15:33.360+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-22T16:15:33.375+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-11-22 16:15:32.032601+00:00
[2024-11-22T16:15:33.388+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stock_price_prediction', 'fetch_data', 'manual__2024-11-22T16:15:32.032601+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/stock_price_prediction_dag.py', '--cfg-path', '/tmp/tmphg851724']
[2024-11-22T16:15:33.393+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask fetch_data
[2024-11-22T16:15:33.395+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=379) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-22T16:15:33.395+0000] {standard_task_runner.py:63} INFO - Started process 380 to run task
[2024-11-22T16:15:33.455+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_price_prediction.fetch_data manual__2024-11-22T16:15:32.032601+00:00 [running]> on host f85d7375f510
[2024-11-22T16:15:33.561+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_price_prediction' AIRFLOW_CTX_TASK_ID='fetch_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-22T16:15:32.032601+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-22T16:15:32.032601+00:00'
[2024-11-22T16:15:33.562+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-22T16:15:35.321+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-22T16:15:35.321+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_price_prediction_dag.py", line 27, in fetch_data_task
    from fetch_data import fetch_data
  File "/external_files/scripts/fetch_data.py", line 2, in <module>
    from vnstock import stock_historical_data
  File "/home/airflow/.local/lib/python3.12/site-packages/vnstock/__init__.py", line 13, in <module>
    from .utils import *
  File "/home/airflow/.local/lib/python3.12/site-packages/vnstock/utils.py", line 56, in <module>
    from IPython.display import display, Markdown, HTML
ModuleNotFoundError: No module named 'IPython'
[2024-11-22T16:15:35.334+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_price_prediction, task_id=fetch_data, run_id=manual__2024-11-22T16:15:32.032601+00:00, execution_date=20241122T161532, start_date=20241122T161533, end_date=20241122T161535
[2024-11-22T16:15:35.348+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 10 for task fetch_data (No module named 'IPython'; 380)
[2024-11-22T16:15:35.377+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-22T16:15:35.398+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-22T16:15:35.401+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
