[2024-11-22T14:49:17.040+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-22T14:49:17.072+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_price_prediction.fetch_data manual__2024-11-22T14:49:16.189039+00:00 [queued]>
[2024-11-22T14:49:17.080+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_price_prediction.fetch_data manual__2024-11-22T14:49:16.189039+00:00 [queued]>
[2024-11-22T14:49:17.081+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-22T14:49:17.095+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-11-22 14:49:16.189039+00:00
[2024-11-22T14:49:17.104+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stock_price_prediction', 'fetch_data', 'manual__2024-11-22T14:49:16.189039+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/stock_price_prediction_dag.py', '--cfg-path', '/tmp/tmpowmerbe1']
[2024-11-22T14:49:17.108+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask fetch_data
[2024-11-22T14:49:17.112+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=300) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-22T14:49:17.113+0000] {standard_task_runner.py:63} INFO - Started process 302 to run task
[2024-11-22T14:49:17.163+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_price_prediction.fetch_data manual__2024-11-22T14:49:16.189039+00:00 [running]> on host 53dfb9592961
[2024-11-22T14:49:17.255+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_price_prediction' AIRFLOW_CTX_TASK_ID='fetch_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-22T14:49:16.189039+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-22T14:49:16.189039+00:00'
[2024-11-22T14:49:17.256+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-22T14:49:17.290+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-22T14:49:17.291+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_price_prediction_dag.py", line 25, in fetch_data_task
    from scripts.fetch_data import fetch_data
ModuleNotFoundError: No module named 'scripts.fetch_data'
[2024-11-22T14:49:17.300+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_price_prediction, task_id=fetch_data, run_id=manual__2024-11-22T14:49:16.189039+00:00, execution_date=20241122T144916, start_date=20241122T144917, end_date=20241122T144917
[2024-11-22T14:49:17.311+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2 for task fetch_data (No module named 'scripts.fetch_data'; 302)
[2024-11-22T14:49:17.327+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-22T14:49:17.348+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-22T14:49:17.350+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
