[2024-11-23T01:53:01.683+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-23T01:53:01.859+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_price_prediction.AUM_workflow.fetch_data manual__2024-11-23T01:52:07.286051+00:00 [queued]>
[2024-11-23T01:53:02.017+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_price_prediction.AUM_workflow.fetch_data manual__2024-11-23T01:52:07.286051+00:00 [queued]>
[2024-11-23T01:53:02.018+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-23T01:53:03.006+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): AUM_workflow.fetch_data> on 2024-11-23 01:52:07.286051+00:00
[2024-11-23T01:53:03.027+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1563) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-23T01:53:03.030+0000] {standard_task_runner.py:63} INFO - Started process 1583 to run task
[2024-11-23T01:53:03.029+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stock_price_prediction', 'AUM_workflow.fetch_data', 'manual__2024-11-23T01:52:07.286051+00:00', '--job-id', '129', '--raw', '--subdir', 'DAGS_FOLDER/stock_price_prediction_dag.py', '--cfg-path', '/tmp/tmphv1_1l7w']
[2024-11-23T01:53:03.035+0000] {standard_task_runner.py:91} INFO - Job 129: Subtask AUM_workflow.fetch_data
[2024-11-23T01:53:03.245+0000] {task_command.py:426} INFO - Running <TaskInstance: stock_price_prediction.AUM_workflow.fetch_data manual__2024-11-23T01:52:07.286051+00:00 [running]> on host ad983beda88b
[2024-11-23T01:53:03.676+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_price_prediction' AIRFLOW_CTX_TASK_ID='AUM_workflow.fetch_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-23T01:52:07.286051+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-23T01:52:07.286051+00:00'
[2024-11-23T01:53:03.682+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-23T01:53:07.664+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/vnstock/__init__.py:18 UserWarning: Vui lòng chuyển đổi sang Vnstock3 thế hệ mới (3.1.0) với câu lệnh: `pip install vnstock3 --upgrade`.
Từ 1/1/2025, vnstock3 sẽ được cài đặt khi sử dụng cú pháp `pip install vnstock` thay cho Vnstock Legacy hiện tại.
Xem chi tiết [chuyển đổi sang vnstock3](https://vnstocks.com/docs/tai-lieu/migration-chuyen-doi-sang-vnstock3).
Phiên bản Vnstock Legacy (0.2.9.2.3) bạn đang sử dụng sẽ không được nâng cấp thêm.
Từ 7/10/2024 Vnstock giới thiệu nhóm Facebook Cộng đồng Vnstock, tham gia thảo luận tại đây: https://www.facebook.com/groups/vnstock.official
[2024-11-23T01:53:07.669+0000] {fetch_data.py:10} INFO - Directory data/raw created or already exists.
[2024-11-23T01:53:07.856+0000] {logging_mixin.py:188} INFO - Error in API response {"status":400,"code":"BAD_REQUEST","message":"invalid symbol"}
[2024-11-23T01:53:07.857+0000] {logging_mixin.py:188} INFO -  
[2024-11-23T01:53:07.857+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-23T01:53:07.858+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_price_prediction_dag.py", line 45, in fetch_data_task
    fetch_data(stock_name)
  File "/external_files/scripts/fetch_data.py", line 13, in fetch_data
    data = stock_historical_data(stock_name, "2005-01-01", "2024-11-1")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/vnstock/technical.py", line 24, in stock_historical_data
    df = ohlc_data(symbol, start_date, end_date, resolution, type, headers=entrade_headers)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/vnstock/technical.py", line 191, in ohlc_data
    return df
           ^^
UnboundLocalError: cannot access local variable 'df' where it is not associated with a value
[2024-11-23T01:53:07.875+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_price_prediction, task_id=AUM_workflow.fetch_data, run_id=manual__2024-11-23T01:52:07.286051+00:00, execution_date=20241123T015207, start_date=20241123T015301, end_date=20241123T015307
[2024-11-23T01:53:07.891+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 129 for task AUM_workflow.fetch_data (cannot access local variable 'df' where it is not associated with a value; 1583)
[2024-11-23T01:53:07.938+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-23T01:53:07.975+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-23T01:53:07.977+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
